### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by cukal** [fralau/mkdocs_macros_plugin#1]
Had to update setup.py to use repackage==0.6, otherwise it wouldn't install. 
btw, really great plugin, thanks!

**Comment by dsikes** [comment]
@cukal  Thanks! I had to do the same. For some reason it also kept failing due to not being able to find the README.md file used in the Long Description in setup.py

Here is a screenshot of the error I was getting:

![image](https://user-images.githubusercontent.com/8764573/43609755-da52247a-9672-11e8-85d9-75cc360616bf.png)

Love the plugin though! It works really well once it is installed. Great work!

**Comment by snelweg** [comment]
wow, thanks! That fixed it for me too.

**Comment by fralau** [comment]
I have written this module for python3. Any way you could use python3 instead of python2?

**Comment by snelweg** [comment]
> I have written this module for python3

I was using it on a machine with LinuxCNC, that uses python2.
Now using a fresh vps, python3 and it all works.

Thank you!

**Comment by fralau** [comment]
Note that `repackage` package should be fixed as well. Thanks for the feedback.
