### ISSUE TITLE
fix_url doesn't return url relative to root dir

### ISSUE THREAD

**Issue by CrispyDrone** [fralau/mkdocs_macros_plugin#32]
Hi,

I have the following directory structure:
```
.
 |-docs
 | |-index.md
 | |-issues
 | | |-index.md
 |-files
 | |-bug-template.txt
 |-main.py
 |-mkdocs.yml
```

I used the example code to create a button:
```python
def define_env(env):

    # import the predefined macro
    fix_url = env.variables.fix_url # make relative urls point to root

    @env.macro
    def button(label, url):
        "Add a button"
        url = fix_url(url)
        HTML = """<a class='button' href="%s">%s</a>"""
        return HTML % (url, label)
```

I've added the following ninja directives to the issues/index.md file:

```
{{ button('Download bug template', 'files/bug-template.txt') }}  
```

However when I investigate the html that gets generated, the href links are of the nature "../files/bug-template.txt" instead of "../../files/bug-template.txt". When I click on the button I receive a 404 response.

![image](https://user-images.githubusercontent.com/37639058/81448996-9da60a00-917f-11ea-8a9e-1b43000c5042.png)

When I move the `bug-template.txt` file to `docs/files/` then it works correctly.

Am I interpreting the documentation incorrectly?

Thanks

**Comment by fralau** [comment]
Yes, the assumption in the example was that `docs/files`. The `docs` directory is the umbrella directory where I would put everything related to my pages including attachments. Note, however, that is not necessarily the best option in all situations (see the case of include of markdown documents #19).

Since this part of the doc is only meant to show how to write a simple macro (something you write for your own requirements), it is up to you. My recommendation is that you trust your personal idea of how things should be done.

**Comment by CrispyDrone** [comment]
In that case, I think the documentation on the website needs to be updated?

![image](https://user-images.githubusercontent.com/37639058/81732633-0bf51000-9491-11ea-9195-0a319e901f04.png)

since it explicitly mentions:
```
The fix_url function is optional. Its purpose is to capture relative urls and make them point to the root of the website, rather than to the docs directory.
```

**Comment by fralau** [comment]
fix_url() was not used in this case (it's used for links in an HTML context).

But yes you are raising a legitimate issue: there are different and not always consistent working directories, for relative links. The problem is that depending on what context, your expectations would be different. 

So far, I used a "natural" approach (**principle of least astonishment**), on a case by case basis. In the case of HTML, you want your hyperlinks in the webpage to work in the most natural way. In the case of markdown includes, you would normally think of the reference directory in such and such way.

There is no definitive answer to that question.

**But that's the point of macros**: **freedom**. You write your macros, to suit your own vision of things and go where you want to go. I do not have to restrict your freedom by telling you where to go (apart of giving you ahint). 

You should change the code I gave you.

There is also a benefit for me: you don't have to restrict my freedom my telling me where to go, so that I can allow you to go  where you want to go (🤔 sound's complicated by I hope it makes sense... 🙂).

**Comment by fralau** [comment]
Right. The penny dropped.

You meant:

If I correct as:

> The `fix_url` function is optional. Its purpose is to capture relative urls
>     and make them point the `docs` directory, rather than `doc/sites`.

Would that sound clearer?

**Comment by fralau** [comment]
OK to close this issue?

**Comment by CrispyDrone** [comment]
Yeah, sorry I've been a bit busy with work.
