### ISSUE TITLE
Failed to import installed module

### ISSUE THREAD

**Issue by wy-z** [fralau/mkdocs_macros_plugin#49]
How about `return importlib.import_module(module_name)` here?
https://github.com/fralau/mkdocs_macros_plugin/blob/4fbcc74849f47ab373478859371bff82876238c5/macros/util.py#L31

**Comment by fralau** [comment]
If my understanding is correct, you would like the function `import_module()` to return a value instead of `None` ?  

The function exists for its side-effect, and the calling program knows (in principle) what module it is trying to import. What type of information do you have in mind ?

Is there a particular use case you see for that ?

**Comment by wy-z** [comment]
@fralau Thank you for everything you’ve done ~
The `module_name` is `foo.macros`, and I install it by `pip install -e .`.
The trouble is that `mkdocs_macros_plugin` can't load it~

**Comment by wy-z** [comment]
@fralau I think we should try to `importlib.import_module(module_name)` even if there is no `pathname_dir` ~
https://github.com/fralau/mkdocs_macros_plugin/blob/4fbcc74849f47ab373478859371bff82876238c5/macros/util.py#L17

**Comment by fralau** [comment]
"If it ain't broke, don't fix it." Is there a bug?

**Comment by wy-z** [comment]
`v0.4.9` works fine, but `0.4.13+` not. @fralau

**Comment by fralau** [comment]
Can you show me what arguments you put in your `mkdocs.yml` under the macro plugin ?

**Comment by wy-z** [comment]
![Uploading image.png…]()

**Comment by wy-z** [comment]
![image](https://user-images.githubusercontent.com/4213483/95564753-d5c4b800-0a51-11eb-8df3-abca3077c43e.png)

**Comment by wy-z** [comment]
![image](https://user-images.githubusercontent.com/4213483/95564867-f68d0d80-0a51-11eb-8c74-446cd91b5936.png)

**Comment by wy-z** [comment]
![image](https://user-images.githubusercontent.com/4213483/95565002-26d4ac00-0a52-11eb-98a5-4aeb071f5c7a.png)

**Comment by fralau** [comment]
Wow. I had never thought about such a use case, with a preinstalled package. 🤔 

Let's say it "accidentally worked" before...

It was never meant to work that way; the module (file `main.py` or directory `main`) is supposed to be in the source directory of your project. 

Is there a reason why you did not wish to install it there ?

**Comment by wy-z** [comment]
I use `mkdocs` and `macros` to manage multiple books in a project.
`xum.macros.py` defines macros, `xum.mkdocs.py` defines `mkdocs` hooks.
Putting "macros.py" everywhere will get dirty~

**Comment by fralau** [comment]
I see how it would good practice to keep your python functions (potential macros) in a predefined module.

On the other hand, would it really a nuisance to have one python module for the hooks, in each project ? Then you could decide which functions you want to export, for each project ?

At least, in my view, each project is slightly different, which is why I want to be able to predefine which macros, filters, variables, etc. I want to make available.

e.g.

```yaml
from xum.macros import foo, bar, baz

def define_env(env):
    """
    This is the hook for the functions (new form)
    """
   for  fn in (foo, bar, baz): 
       env.macro(fn)
```

Or else 🤔 , if you want to import all of it, wholesale:

```yaml
from inspect import getmembers, isfunction
import xum.macros

def define_env(env):
    """
    This is the hook for the functions (new form)
    """
    # make a dictionary of macros (out of tuples)
    macros = dict(getmembers(xum.macros, isfunction))

    # turn the variables into macros
    env.variables.update(macros)
```

I guess you could reduce the boilerplate, with an ad-hoc function `get_functions(module)` which would return a dictionary. 🤔

**Comment by wy-z** [comment]
My use case may be a little different.
I made a general-purpose user manual generator using `mkdocs` and `macros`, the generator supports `component` and `macro`.
Writers only need to care about component references and a few special macros, so I have to put `xum/macros.py` and `xum/mkdocs.py` to an installable package.

**Comment by fralau** [comment]
If you use a generator, it's even better: woudn't it be easy to auto-generate the `main.py` file ?

**Comment by fralau** [comment]
@wy-z To give a little background, the old import system was changed, to avoid modules to be accidentally imported when they are not in the project's directory (homonyms). This was changed, because this ambiguity caused a failure in some contexts (#40).

Basically, you exploited that ambiguity to your advantage.

**Comment by makkus** [comment]
I am having a similar issue to @wy-z, and I would prefer to load a module in the current virtual env to an actual file in the project.

Overall, I guess the way you do it works for most cases, but I can think of quite a few valid use-cases where having the option to load a module from the current Python env would be required. I have described my personal usage of mkdocs-macros in issue #43, and I'd be happy to elaborate more if this doesn't make much sense in this context here.

I can totally understand if you don't want to change any of this (and potentially break existing usage), but in the spirit of providing another perspective, I would like to provide mine (looking in from the outside):

- the configuration option is called 'module_name' but I think what you currently really want from the user is the path to the module. In my mind 'module_name' is already present in the environment/PYTHONPATH, and I don't have to care where exactly it is. Python will take care of it as always. If the option was called 'module_path' (or similar), it would be less ambiguous (at least to me). What adds to this impression is that I don't need to specify the '.py' extension, which really makes me think this will use standard Python module loading, not some custom thing that is specific to this library.

- the default configuration file is called 'main.py' -- as someone not knowing anything about mkdocs, this filename indicates a much more important function within a project than containing helper functions for documentation generation - I think it should be called 'mkdocs-macros-env.py' or 'mkdocs-macros-main.py' or something like that. This would also make any ambiguity way less likely.

- the [documentation](https://mkdocs-macros-plugin.readthedocs.io/en/latest/python/#location-of-the-module) for this functionality does not explicitly explain what this configuration option does (at least I was mistaken when reading it)

Personally, I would appreciate if mkdocs would support both use-cases: load from file, or from environment. For more advanced users, it would be cool if the lookup mechanism was something like:

- look whether there exists a file named after the configuration option
- if not, try to load the module from the environment
- print out a log message which one was chose (alongside the other log messages that already exist)

This would not break any existing setups, it would only add a little bit of ambiguity which would be relatively transparent because of the log message. 

If you don't like that solution, maybe an additional configuration option would be possible? Something like 'module_name_in_env' (can't think of a really good name right now) and if both 'module_name' and 'module_name_in_env' are specified, an exception is thrown?

**Comment by fralau** [comment]
@makkus @wy-z  I've given it a good thought, and yes: it makes sense. 

I have been working on an argument (`modules`) that would be a list of modules to be imported.

e.g. :

```yaml
  - macros:
      modules: [mkdocs_test_macro]
```

I thought that providing more than one might be useful. Would that work for you?

**Comment by fralau** [comment]
> Personally, I would appreciate if mkdocs would support both use-cases: load from file, or from environment. For more advanced users, it would be cool if the lookup mechanism was something like:
> 
>     * look whether there exists a file named after the configuration option
> 
>     * if not, try to load the module from the environment
> 
>     * print out a log message which one was chose (alongside the other log messages that already exist)

@makkus I have thought about that, but there is one flaw: there could be a `main` module somewhere, totally by chance, and one could have unexpected behaviors, which do not make sense. In my understanding, this is what had actually occured in #40

Which is why I thought of another parameter, `modules`.

💡 Plus that could be used by people who want to publish their own set of functions on github/pypi?   🤔

**Comment by makkus** [comment]
> @makkus I have thought about that, but there is one flaw: there could be a `main` module somewhere, totally by chance, and one could have unexpected behaviors, which do not make sense. In my understanding, this is what had actually occured in #40

Agreed, this is why I mentioned having 'main' as the default name is not optimal. If the default name was something like 'mkdocs-macros-main' that would never happen. And if it would, I would deserve everything that is coming to me :-)

I think the 'modules' parameter would be even better than what I suggested. I can see this being really useful in the long run, esp. as you say people can start writing macros that are re-usable. I already sorta do that for my own internal use, and I find that highly efficient. I'm probably over-enthusiastic, but there is a lot of power in the idea behind such re-useable macros, and in my mind it would improve mkdocs usefulness considerably.

Just to confirm my understanding: the 'main.py' file would be totally optional with this, right?

**Comment by fralau** [comment]
> Just to confirm my understanding: the 'main.py' file would be totally optional with this, right? If so, we'd get the best of both worlds. It'd be ideal if 'modules' would load before 'main.py', so that main.py can import code from the former...

Absolutely !

**Comment by fralau** [comment]
OK I made a first implementation, that should work. 

Example:

```yaml
plugins:
  - search
  - macros:
      include_dir: include
      modules: [mkdocs_macros_test]
```

The package `mkdocs_macros_test` is on pypi, so it should install automagically with the new version.

I'm open to suggestions.

**Comment by fralau** [comment]
Let me know if it works as you expect. 

Did you meet any issues?

Any ideas on naming conventions for the modules? Should the plugin be opinionated about those conventions?

**Comment by makkus** [comment]
Sorry, haven't had time yet to test it out. Just tried now, and I'm getting an error (below). I've updated my example repo from the other issue to use the new 'modules' config option, so it should be easy to reproduce: https://github.com/makkus/mkdocs_macros_regression

In this case, the 'ci.docs' module is in the Python environment (as can be tested by using a REPL and doing ``from ci import docs``, but the macros plugin spits out:

```
❯ mkdocs build
[macros] Macros arguments: {'module_name': 'main', 'modules': ['ci.docs'], 'include_dir': '', 'include_yaml': [], 'j2_block_start_string': '', 'j2_block_end_string': '', 'j2_variable_start_string': '', 'j2_variable_end_string': ''}
[macros] Preinstalled modules: ci.docs
Traceback (most recent call last):
  File "/home/markus/temp/mkdocs_macros_regression/.direnv/python-3.8.5/lib/python3.8/site-packages/macros/plugin.py", line 226, in _load_module
    module = importlib.import_module(module_name)
  File "/home/markus/.asdf/installs/python/3.8.5/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ci'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/markus/temp/mkdocs_macros_regression/.direnv/python-3.8.5/bin/mkdocs", line 8, in
 <module>
    sys.exit(cli())
  File "/home/markus/temp/mkdocs_macros_regression/.direnv/python-3.8.5/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/markus/temp/mkdocs_macros_regression/.direnv/python-3.8.5/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/markus/temp/mkdocs_macros_regression/.direnv/python-3.8.5/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/markus/temp/mkdocs_macros_regression/.direnv/python-3.8.5/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/markus/temp/mkdocs_macros_regression/.direnv/python-3.8.5/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/markus/temp/mkdocs_macros_regression/.direnv/python-3.8.5/lib/python3.8/site-packages/mkdocs/__main__.py", line 152, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/home/markus/temp/mkdocs_macros_regression/.direnv/python-3.8.5/lib/python3.8/site-packages/mkdocs/commands/build.py", line 236, in build
    config = config['plugins'].run_event('config', config)
  File "/home/markus/temp/mkdocs_macros_regression/.direnv/python-3.8.5/lib/python3.8/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/home/markus/temp/mkdocs_macros_regression/.direnv/python-3.8.5/lib/python3.8/site-packages/macros/plugin.py", line 337, in on_config
    self._load_module()
  File "/home/markus/temp/mkdocs_macros_regression/.direnv/python-3.8.5/lib/python3.8/site-packages/macros/plugin.py", line 234, in _load_module
    raise ModuleNotFoundError("Could not import installed "
ModuleNotFoundError: Could not import installed module 'ci.docs' (missing?)
```

**Comment by fralau** [comment]
@makkus Python, why so much hatred? 😰

**Comment by wy-z** [comment]
![image](https://user-images.githubusercontent.com/4213483/96689909-9a14e100-13b5-11eb-84f4-757372cc2b54.png)
This fix works well for me.
Thanks again. @fralau @makkus

**Comment by fralau** [comment]
@wy-z Thanks, this is a relief.

@makkus Just to make sure we are all on the same track, are you positive that your package is working properly, if you call it from the REPL?

For may part, I get:

```
$ python
Python 3.8.5 (default, Jul 21 2020, 10:42:08)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ci
>>> help(ci)

>>> from ci import docs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/DUO/laurent/Documents/GitHub/mkdocs_macros_regression/ci/docs/__init__.py", line 9, in <module>
    from pydoc_markdown.main import RenderSession
ModuleNotFoundError: No module named 'pydoc_markdown'
>>> import ci.docs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/DUO/laurent/Documents/GitHub/mkdocs_macros_regression/ci/docs/__init__.py", line 9, in <module>
    from pydoc_markdown.main import RenderSession
ModuleNotFoundError: No module named 'pydoc_markdown'
>>>
```

Of course, this may or may not be relevant.

**Comment by makkus** [comment]
Interesting, not sure what exactly is different in our environments:

```
❯ python
Python 3.8.5 (default, Sep 18 2020, 11:44:19)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ci
>>> help(ci)
  Help on package ci:

  NAME
      ci

  PACKAGE CONTENTS
      docs (package)

  FILE
      (built-in)


>>> from ci import docs
>>>
```

Maybe it's something to do that you are using Mac OS X and I Linux? Or maybe that the 'ci' package is an [implicit namespace package](https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages)? I wouldn't think so since you are using the same version of Python as me... Do you get the same error if you create an empty '__init__.py' file under the 'ci' folder?

**Comment by makkus** [comment]
Ah, did you install the package using ``pip install '.[docs']'``? Otherwise you might have missed the dependencies that are used for doc generation. My pip list in this environment is:

```
❯ pip list
Package                    Version
-------------------------- -----------------
actdiag                    2.0.0
anyio                      2.0.2
appdirs                    1.4.4
asyncclick                 7.1.2.2
blockdiag                  2.0.1
certifi                    2020.6.20
chardet                    3.0.4
click                      7.1.2
deepdiff                   5.0.2
docspec                    0.2.0
docspec-python             0.0.7
formic2                    1.0.3
funcparserlib              0.3.6
future                     0.18.2
idna                       2.10
Jinja2                     2.11.2
joblib                     0.17.0
livereload                 2.6.3
lunr                       0.5.8
Markdown                   3.3.2
markdown-blockdiag         0.7.0
markdown-include           0.6.0
MarkupSafe                 1.1.1
mkdocs                     1.1.2
mkdocs-macros-plugin       0.4.19.post0
mkdocs-macros-test         0.1.0
mkdocs-material            6.1.0
mkdocs-material-extensions 1.0.1
mkdocs-simple-hooks        0.1.1
nltk                       3.5
nr.collections             0.0.1
nr.databind.core           0.0.21
nr.databind.json           0.0.13
nr.fs                      1.6.2
nr.interface               0.0.3
nr.metaclass               0.0.5
nr.parsing.date            0.4.2
nr.pylang.utils            0.0.3
nr.stream                  0.0.4
nr.sumtype                 0.0.3
nr.utils.re                0.1.0
nwdiag                     2.0.0
ordered-set                4.0.2
pathtools                  0.1.2
Pillow                     8.0.0
pip                        20.1.1
pip-licenses               2.3.0
PTable                     0.9.2
pydoc-markdown             3.5.0
Pygments                   2.7.1
pymdown-extensions         8.0.1
python-dateutil            2.8.1
PyYAML                     5.3.1
regex                      2020.10.15
requests                   2.24.0
seqdiag                    2.0.0
setuptools                 47.1.0
six                        1.15.0
sniffio                    1.2.0
termcolor                  1.1.0
tingex                     0.1.dev3+g8c4aad2
toml                       0.10.1
tornado                    6.0.4
tqdm                       4.50.2
urllib3                    1.25.11
uvloop                     0.14.0
watchdog                   0.10.3
watchgod                   0.6
webcolors                  1.11.1
```

**Comment by fralau** [comment]
OK. You used the `module_name` argument (local module) instead of `modules` (list of preinstalled modules).

This worked for me:
```yaml
plugins:
- search
- macros:
   module: [ci.docs]
```

**Comment by fralau** [comment]
@makkus OK. You used the `module_name` parameter (local module) instead of `modules` (list of preinstalled modules).

This worked for me:

```yaml
plugins:
- search
- macros:
   modules: [ci.docs]
```

**Comment by makkus** [comment]
@fralau I'm not sure I follow. I'm pretty sure I used ``modules``: https://github.com/makkus/mkdocs_macros_regression/blob/master/mkdocs.yml

Also, the output in the error message I posted above contains:
```
❯ mkdocs build
[macros] Macros arguments: {'module_name': 'main', 'modules': ['ci.docs'], 'include_dir': '', 'include_yaml': [], 'j2_block_start_string': '', 'j2_block_end_string': '', 'j2_variable_start_string': '', 'j2_variable_end_string': ''}
[macros] Preinstalled modules: ci.docs
```

Good to hear that it worked for you though, so it's probably just a small issue related to configuration or somesuch. I'll try again later, maybe I can get to the bottom of it myself.

**Comment by fralau** [comment]
Perhaps I got myself confused, but here is what I got. At least it displays a page:

```
$ mkdocs serve
INFO    -  Building documentation...
WARNING -  Config value: 'plugins'. Warning: ('modules', 'Unrecognised configuration name: modules')
[macros] Macros arguments: {'module_name': 'main', 'include_dir': '', 'include_yaml': [], 'j2_block_start_string': '', 'j2_block_end_string': '', 'j2_variable_start_string': '', 'j2_variable_end_string': '', 'modules': ['ci.docs']}
[macros] Project dir 'snip/GitHub/mkdocs_macros_regression'
[macros] Variables: ['extra', 'config', 'environment', 'plugin', 'git', 'context', 'macros_info', 'now', 'fix_url']
[macros] Extra variables (config file): {}
[macros] Filters: {'pretty': <function define_env.<locals>.pretty at 0x10cd2a670>}
[macros] Docs directory: snip/GitHub/mkdocs_macros_regression/docs
[macros] Includes directory: snip/GitHub/mkdocs_macros_regression/docs
INFO    -  Cleaning site directory
WARNING -  A relative path to 'api-documentation.md' is included in the 'nav' configuration, which is not found in the documentation files
INFO    -  Documentation built in 0.56 seconds
[macros] We will also watch: []
[I 201021 19:06:53 server:335] Serving on http://127.0.0.1:8000
INFO    -  Serving on http://127.0.0.1:8000
[I 201021 19:06:53 handlers:62] Start watching changes
INFO    -  Start watching changes
[I 201021 19:06:53 handlers:64] Start detecting changes
INFO    -  Start detecting changes
```

**Comment by makkus** [comment]
Oh:
```
WARNING -  Config value: 'plugins'. Warning: ('modules', 'Unrecognised configuration name: modules')
```
Did you update mkdocs-macros-plugin' to the dev version? Sorry, I forgot to mention you will have to do that. As it is, 'setup.cfg' is configured to just use the latest version from pypy, and your recent changes haven't made it there yet.

**Comment by fralau** [comment]
@makkus  Of course. You would have to use the latest version on github.

**Comment by makkus** [comment]
@fralau sorry, I'm not sure we are on the same page. So, just to be clear: I was trying to use my example repo from the other issue to demonstrate how the current dev version of the macros plugin throws an error in that particular setup. I did use that dev version in my test, but it looks like you didn't. Did I get that right?

If so, there does seem to be an issue with importing modules in certain circumstances. I'm happy to look into it a bit more tomorrow or the day after, if you want. It might be an edge case nobody else will likely encounter anytime soon. But I reckon it would still be good to at least figure out why it's failing...

**Comment by fralau** [comment]
Sure: just to summarize I downloaded your repo as is, I followed your instructions and the MkDocs server started properly.

As far as I can tell, **the plugin's code seems to works properly**. If a module can be called with an `import` on the REPL, then it will presumably be available to the plugin.

After all, it just calls [`importlib.import_module()`](https://docs.python.org/3/library/importlib.html), which essentially does the work of `import`.


That's the totality of the relevant code:

```python
        for module_name in modules:
            try:
                module = importlib.import_module(module_name)
                if hasattr(module, 'define_env'):
                    module.define_env(self)
                else:
                    raise NameError("No valid function found "
                                    "in installed module '%s'" %
                                    module_name)
            except ModuleNotFoundError:
                raise ModuleNotFoundError("Could not import installed "
                                          "module '%s' (missing?)" % 
                                          module_name,
                                          name=module_name)
```

In sum, your example worked as it should

**Comment by makkus** [comment]
Right, but the repo was written for the other issue, which is why it doesn't include the latest dev version of the macros plugin (I only updated 'mkdocs.yml' to include the config change, 'setup.cfg' still has a dependency on the macros plugin with no specified version). To test it with your new version, you will have to update the plugin in that environment. As I wrote, in the log output you posted there was this message:

```
$ mkdocs serve
INFO    -  Building documentation...
WARNING -  Config value: 'plugins'. Warning: ('modules', 'Unrecognised configuration name: modules')
```

Which means it didn't even it didn't even try to load the module since the version you are using does not yet support the 'modules' config option. I can change the setup.cfg if you want me to, but I figured its easy enough to do a ``pip install -U git+https://github.com/fralau/mkdocs_macros_plugin.git`` which is why I didn't bother so far.

**Comment by fralau** [comment]
@makkus 🙂 Whatever the case may be, the plugin seems OK to me, and I managed to make it work with your project.

**Comment by makkus** [comment]
Sorry @fralau , I sense I'm starting to annoy you with my inability to explain to you why this is not the case, and what you are seeing is to be expected, but still wrong. Apologies for that, I don't know how else to explain it.

Before I stop trying, would you mind confirming the version of mkdocs-macros-plugin you are using when you test my project? I would bet the version in your environment is the latest release from pypy, am I right? The output of a simple ``pip list`` will do.

**Comment by makkus** [comment]
Ok, I found a few minutes and started debugging this issue, I guess that is more efficient than you having to figure out how to reproduce the issue. It's a weird one. My best guess is that it has to do with some magic mkdocs is doing in regards to loading of modules. I wrote a standalone-script that basically is the code from [your comment here](https://github.com/fralau/mkdocs_macros_plugin/issues/49#issuecomment-714223993), just without anything mkdocs-related. Running that in the same environment as the (failing) ``mkdocs build`` command works fine. 

This is in line with my other successful attempts to loading that module (via Python REPL, ``python -c 'import importlib; importlib.import_module("ci.docs")'``, etc.). Since all those work, I assume it has to be mkdocs related. 

Unless you know more about how mkdocs itself loads its modules than I do, I suggest we just assume this is an edge-case the 'mkdocs-macros-plugin' can't really do anything about, and it would have to be fixed in mkdocs itself. Looking at your code, I wouldn't know what to do differently either, and I can use a work-around to fix my specific issue.

I wouldn't be surprised if somebody else stumbles upon this later on, after/if the ``modules`` config option sees some adoption. We can always try to look at it again then, with new data.

**Comment by fralau** [comment]
Yes I admit I was completely lost with your environment, especially since it uses a `direnv`.  It turns out it does not use the last version of `mkdocs-macros`:


```yaml
mkdocs                     1.1.2
mkdocs-macros-plugin       0.4.18
mkdocs-material            6.1.0
mkdocs-material-extensions 1.0.1
mkdocs-simple-hooks        0.1.1
```

This example is very complicated and I'm not sure what the components are doing and why.  I'm afrait I'm on uncharted waters. 

Would you be able to devise a simpler example, with a barematel package, where this fails? (And possibly without a direnv?)

**Comment by makkus** [comment]
Yes, sorry for this, I just boiled down my normal Python template to showcase the (other) issue, this was less than ideal for using to show the new issue. The direnv part should not matter much, since you can just use your own way of creating a virtualenv, but you are right, a more minimal example would be much better overall.

I'll try to throw something together over the weekend, but as I said, I'm fairly certain that even if we manage to reproduce the issue reliably, a potential fix would most likely not happen in this package, but upstream mkdocs itself...

**Comment by fralau** [comment]
Hi @makkus , did you have the opportunity to have a look at this ?

**Comment by makkus** [comment]
Oh, sorry, totally slipped my mind. I don't think I'll be able to in the next few days. How about you close this issue and we assume this works for all the relevant cases (as it seems to work fine for @wy-z). I plan to re-vamp my Python project template, and factor out some of my mkdocs-macros related functions into it's own library, using the new 'modules' config option. If I stumble upon problems with that new layout I'll open a new issue?

**Comment by fralau** [comment]
@makkus That sounds fine for me. 👍 

I wish you good success with your project, and by all means let me know if you encounter any issue !

**Comment by fralau** [comment]
This will be made available on pypi.
