### ISSUE TITLE
Save macros as environment globals

### ISSUE THREAD

**Issue by briankchan** [fralau/mkdocs_macros_plugin#81]
[Currently, the plugin renders pages with all variables/macros in the template context](https://github.com/fralau/mkdocs_macros_plugin/blob/f4ad1a139763818f8dfc099dd03b5c12999c0d4f/mkdocs_macros/plugin.py#L443); this means that these variables/macros are not accessible when [importing/including without context](https://jinja.palletsprojects.com/en/2.11.x/templates/#import-context-behavior).

For variables, this is consistent with mkdoc's behavior, but for macros, I feel that it's a bit counterintuitive. Personally, I think macros should be added to the [environment globals](https://jinja.palletsprojects.com/en/2.11.x/api/#jinja2.Environment.globals) instead so that they're always usable--this would match the behavior for filters.

**Comment by fralau** [comment]
@briankchan Thank you for opening this issue: you are making a very interesting and new point. 

To me, macros have been variables just as any other. Could you explain in little more details (with examples and counter-examples) why macros should be in Jinja2's global context, instead of the template's context?

In the event, would there be a clear way to draw the line between variables and macros?

**Comment by honzajavorek** [comment]
Perhaps on a similar note, I grapple with the fact that `fix_url()` is not available for the macros if I import them from a separate file. That essentially means I must import with context everything, effectively ruining any kind of encapsulation of the macros. I do pass them variables in arguments, but I could access them just like that, too, as the context must be there, which causes me distress.

I'm happy to contribute. Not that I'd know how to change this, but for me it's worth changing. Not sure if this wouldn't be as a breaking change to the plugin's interface though 🤔

**Comment by fralau** [comment]
@honzajavorek I am grokking, more or less, what the argument is about, but I would really need some examples and counter-examples. 🙂

**Comment by honzajavorek** [comment]
In my case I'm referring to macros which I wrote in Jinja2, and I saved to, let's say, `includes.html`:

```jinja2
{% macro something(items, items_count) %}
<h3>{{ items_count }} awesome items</h3>
<div class="items">
  {% for item in items %}...{% endfor %}
</div>
{% endmacro %}
```

And then I want to import them using `{% from 'includes.html' import something %}` to the actual Markdown documents. But let's say these macros use `fix_url()`, because they need to link images or other pages. In that case, `{% from 'includes.html' import something %}` will fail. I need to do `{% from 'includes.html' import something with context %}`. That feels too explicit (when importing the macros, I need to think whether they link stuff or not) and also leaks everything else currently in the context to the scope of the macro (can lead to unexpected bugs). If `fix_url()` could somehow become "global", for these macros, that would solve my distress. That said, I hope I'm not hijacking the issue for a problem unrelated to the original poster, but I really think it's a similar thing.

(Side note: I do all this as it allows me to have something like reusable components. Ideal for someone who likes Jinja2 and dislikes post-2014 modern frontend frameworks like React or Vue, which would be probably able to solve the same thing in a different way, see [MDX](https://mdxjs.com/).)

**Comment by honzajavorek** [comment]
Re-reading the original poster's issue, I think it's the same thing, only my is focused to a single manifestation of a larger problem. I think the setting of the scene is the same in what @briankchan describes, but also affects any other macros or filters added by either the plugin itself or by Python code in something like `main.py`.

**Comment by fralau** [comment]
@honzajavorek  Whoah! When you mean macros, you mean _real_ Jinja2 macros, written as Jinja2 and not as Python?

Just curious: what is the reason for prefering writing a Jinja2 macro, rather than a little piece of Python code? (I don't disapprove, I'm just asking). 

OK... 🤔 Would it then make sense, if the _pre-defined_ (default) macros were included in the globals context instead of the template context?

**Corollary question**: how should these be treated in the template context? As `var.globals`?

**Comment by briankchan** [comment]
Jinja2 macros are useful for the same reason we use Jinja2 instead of pure Python to begin with: if there's a bunch of string manipulation involved in a macro, then template code will often be easier to read than equivalent Python code.

Also, by "pre-defined," do you mean macros defined in a `define_env()` using `env.macro`? (That's what I was originally trying to refer to, but I probably wasn't entirely clear about it.) I think just storing these to a separate list and adding them as globals to the environment would be fine; it would look a lot like how `env.filter` currently works. I don't think there's any need to duplicate them in the template context (i.e., `MacrosPlugin.variables`).

**Comment by fralau** [comment]
> Jinja2 macros are useful for the same reason we use Jinja2 instead of pure Python to begin with: if there's a bunch of string manipulation involved in a macro, then template code will often be easier to read than equivalent Python code.

Now that you are mentioning it, it's self-evident. That's what a templating language is for. 🙂 

> Also, by "pre-defined," do you mean macros defined in a `define_env()` using `env.macro`? (That's what I was originally trying to refer to, but I probably wasn't entirely clear about it.) I think just storing these to a separate list and adding them as globals to the environment would be fine; 

_Predefined_ (or perhaps better: _built-in_) for  me are those variables and macros that come out of the box, without the need for a user to define them explicitly in a Python module. [They are defined in `context.py`](https://github.com/fralau/mkdocs_macros_plugin/blob/master/mkdocs_macros/context.py).

That would be a concept more or less equivalent of [built-in](https://docs.python.org/3/library/functions.html) variables and functions in Python, or "[builtin](https://www.gnu.org/software/bash/manual/html_node/Bash-Builtins.html)" for bash.

> it would look a lot like how `env.filter` currently works. 

Yes, [filters are part of the environment](https://docs.python.org/3/library/functions.html). Good point.

> I don't think there's any need to duplicate them in the template context (i.e., `MacrosPlugin.variables`).

I would add them to the variables, anyway, for the same reason I did for filters: auto-discovery, documentation, avoiding exceptions, etc.

**Comment by honzajavorek** [comment]
Exactly as @briankchan wrote. I'd use Python code if it's a small utility (filters usually fall into this category), but macros if it features HTML markup of size larger than one or two inline tags. My use case is components. Real example:

```jinja2
{% macro members_roll(members, members_total_count) %}
<div class="members">
  <ul class="members__items">
    {% for member in members|sample(20) %}
      <li class="members__item">
        <img width="51" height="51" class="members__image" src="{{ fix_url('../static/' + member.avatar_path) }}" alt="Profile picture of a member {{ member.id }}">
      </li>
    {% endfor %}
    <li class="members__item members__item--count">
      and&nbsp;{{ members_total_count - 20 }}&nbsp;more
    </li>
  </ul>
</div>
<p class="button-compartment">
  <a href="{{ fix_url('../club/') }}" class="button">
    Join&nbsp;us
  </a>
</p>
{% endmacro %}
```

This is something I wouldn't like to have as Python code. I can put `{{ members_roll(members, members_total_count) }}` to my Markdown wherever I need and it works.

Looking at this particular example, I'm now realizing I did have a problem to make this work not only because of `fix_url()` not being in the macro context, but also `sample()`, which is my custom-defined filter from `main.py`, not being available. So being able to define filters or macros like this as globals would be nice. In that case the macro could access only globals plus `members` and `members_total_count`, which I pass down as explicit arguments, which seems to me as a reasonable compromise between being explicit to prevent bugs and convenience.

**Comment by fralau** [comment]
So, we would be looking at putting the built-in macros in globals?

@honzajavorek Just to make sure I'm tracking, in order to be able to use `fix_url()` you had to use the `import...with-context` directive?

**Comment by fralau** [comment]
I've got an even more radical idea, which might minimize changes to the code.

Why not import everything as globals?

1. Would that solve your issue?
1. Would that make any difference for the rest of the user base?

**Comment by briankchan** [comment]
Yeah, making all variables global would work, although you'd still need to use template context for variables that change with each page (i.e., `page` itself and the meta-variables from `page.meta`).

It would also be inconsistent with how mkdocs handles its variables, but I don't think it would be a breaking change for most users: it should only matter for templates imported/included without context that for some reason require those variables to be initially undefined.

(Mkdocs source code: [rendering template], which calls [`get_context`] to add vars to context; [creating environment], which calls 
[`get_env`] (without setting any globals))

[rendering template]: https://github.com/mkdocs/mkdocs/blob/6a694fd/mkdocs/commands/build.py#L83
[`get_context`]: https://github.com/mkdocs/mkdocs/blob/6a694fd/mkdocs/commands/build.py#L31
[creating environment]: https://github.com/mkdocs/mkdocs/blob/6a694fd/mkdocs/commands/build.py#L270
[`get_env`]: https://github.com/mkdocs/mkdocs/blob/6a694fd/mkdocs/theme.py#L105

**Comment by honzajavorek** [comment]
I'd be for aligning with how MkDocs work, variables to template context, macros and filters to the global context.

**Comment by fralau** [comment]
🤔  At least, it's a clear position. I would have to think about it, because that would require some redesign. For the moment, variables and [macros are thrown into the same dictionary](https://github.com/fralau/mkdocs_macros_plugin/blob/f636307ec359eccb54782a3cdebe2ac24b5cc5bc/mkdocs_macros/plugin.py#L148). 

I could change that and create a specific dictionary for macros. But it might create some situations for those who had explicitly put their macros into the variables dictionary (thus breaking backward compatibility). 

Or perhaps not: perhaps it will work all the same; but we would have, at best, to deprecate that old behavior.

**Comment by fralau** [comment]
There is one thing like in this idea 🤔: that it would clarify things by clearly separating variables, macros and filters.

I've always found the idea of putting variables and macros in one dictionary, and filters in another, a little counter-intuitive. That violates a little the Principle of Least Astonishment. If macros get their own dictionary, then anyone who browses through the code will know where to look for.

Furthermore, Jinja2 makes an important distinction between macros/functions and variables, when they are missing: 

- for variables, Jinja2 defaults for an empty string
- for macros, it crashes

**Comment by fralau** [comment]
@briankchan and @honzajavorek: this commit should solve the issue. Let me know if it worked for you?

**Comment by briankchan** [comment]
@fralau Yup, that does the trick.

**Comment by fralau** [comment]
@briankchan Thanks a lot! 

A good thing was done 🙂.
